@Tags(['parity'])
library;

import 'dart:convert';
import 'dart:io';

import 'package:pe_core/pe_core.dart';
import 'package:pe_domain/pe_domain.dart';
import 'package:test/test.dart';

/// Cross-validates the Dart port against values produced by the **actual
/// legacy TypeScript** implementations.
///
/// The fixture is generated by `phantom_eye/tool/gen_legacy_fixture.mjs`, which embeds the
/// original `bearingDeg`/`haversine`/`formatDistance`/`formatDuration`/
/// `projectOnRoute` bodies verbatim from `src/`. Running both over identical
/// inputs and demanding agreement is a far stronger guarantee than
/// hand-written expectations — it catches transcription slips that a
/// plausible-looking assertion would happily accept.
///
/// The fixture path is overridable via PE_LEGACY_FIXTURE; when the file is
/// absent the group is skipped so the suite still runs in a clean checkout.
void main() {
  final fixturePath =
      Platform.environment['PE_LEGACY_FIXTURE'] ??
      'test/fixtures/legacy_reference.json';
  final file = File(fixturePath);

  if (!file.existsSync()) {
    // ignore: avoid_print
    print(
      'Skipping legacy parity: no fixture at $fixturePath. Regenerate '
      'from phantom_eye/ with: node tool/gen_legacy_fixture.mjs > '
      'packages/pe_domain/test/fixtures/legacy_reference.json',
    );
    return;
  }

  final data = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;

  final points = <LngLat>[
    const LngLat(-122, 37),
    const LngLat(-121.5, 37.5),
    const LngLat(0, 0),
    const LngLat(10, -20),
    const LngLat(-74.006, 40.7128),
    const LngLat(139.69, 35.68),
  ];

  group('parity with legacy TypeScript', () {
    test('bearingDeg and haversine agree over every point pair', () {
      final expectedBearings = (data['bearings'] as List).cast<num>();
      final expectedHaversines = (data['haversines'] as List).cast<num>();

      var k = 0;
      for (var i = 0; i < points.length; i++) {
        for (var j = 0; j < points.length; j++) {
          if (i == j) continue;
          expect(
            bearingDeg(points[i], points[j]),
            closeTo(expectedBearings[k].toDouble(), 1e-9),
            reason: 'bearing $i->$j',
          );
          expect(
            haversine(points[i], points[j]),
            closeTo(expectedHaversines[k].toDouble(), 1e-6),
            reason: 'haversine $i->$j',
          );
          k++;
        }
      }
      expect(k, expectedBearings.length);
    });

    test('formatDistance agrees, including the 1000 ft boundary quirk', () {
      const inputs = <double>[
        0,
        1,
        30.48,
        100,
        304,
        305,
        1609.344,
        8046.72,
        16093.44,
        160934.4,
        999999,
      ];
      final expected = (data['distances'] as List).cast<String>();
      for (var i = 0; i < inputs.length; i++) {
        expect(
          formatDistance(inputs[i]),
          expected[i],
          reason: 'formatDistance(${inputs[i]})',
        );
      }
    });

    test('formatDuration agrees', () {
      const inputs = <double>[
        0,
        30,
        59,
        60,
        600,
        3599,
        3600,
        3900,
        7200,
        86400,
      ];
      final expected = (data['durations'] as List).cast<String>();
      for (var i = 0; i < inputs.length; i++) {
        expect(
          formatDuration(inputs[i]),
          expected[i],
          reason: 'formatDuration(${inputs[i]})',
        );
      }
    });

    test('windowed route projection agrees across a simulated drive', () {
      final route = <LngLat>[
        for (var i = 0; i < 500; i++)
          LngLat(-122.0 + i * 0.0001, 37.0 + i * 0.00008),
      ];
      final projector = RouteProjector(coordinates: route);
      final expected = (data['projections'] as List)
          .cast<Map<String, dynamic>>();

      var idx = 0;
      for (var seg = 0; seg < 480; seg += 7) {
        final pos = LngLat(
          (route[seg].lon + route[seg + 1].lon) / 2 + 0.00002,
          (route[seg].lat + route[seg + 1].lat) / 2,
        );
        final actual = projector.project(pos);
        final want = expected[idx++];

        expect(
          actual.segmentIndex,
          want['seg'],
          reason: 'segment at drive step $seg',
        );
        expect(
          actual.alongMeters,
          closeTo((want['along'] as num).toDouble(), 1e-6),
          reason: 'along at drive step $seg',
        );
        // 1e-6 deg, not 1e-9: the two runtimes order the same floating-point
        // operations slightly differently, so results diverge in the last
        // couple of ULPs. Measured worst case across this drive is ~1.1e-9
        // deg — about a nanometre of lateral error over a kilometre — so
        // this tolerance is still far beyond any physical significance.
        expect(
          actual.bearing,
          closeTo((want['bearing'] as num).toDouble(), 1e-6),
          reason: 'bearing at drive step $seg',
        );
        expect(
          actual.offsetMeters,
          closeTo((want['offset'] as num).toDouble(), 1e-6),
          reason: 'offset at drive step $seg',
        );
      }
      expect(idx, expected.length);
    });
  });
}
